version: "3.7"

services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./news_admin/app_init.sh
    volumes:
      - ./news_admin:/code
    expose:
      - ${SERVER_PORT:-8000}
    ports:
      - ${SERVER_PORT:-8000}:${SERVER_PORT:-8000}
    restart: on-failure
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-apiserver}
      - POSTGRES_USER=${DB_USER:-dbuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dbpass}
    volumes:
      - ${DB_LOCAL_DATA:-./dbdata}:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_LOCAL_PORT:-5433}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5