# Generated by Django 4.1.2 on 2022-10-24 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('place', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(
                    blank=True, to='categories.category')),
                ('city', models.ForeignKey(
                    blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.city')),
            ],
        ),
        migrations.CreateModel(
            name='HeadlineVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='headline_vid', validators=[
                 django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='videos_headline', to='headlines.headline')),
            ],
        ),
        migrations.CreateModel(
            name='HeadlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='headline_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='images_headline', to='headlines.headline')),
            ],
        ),
    ]
